<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-AsyncReportEngine.Worker-3e3d58b1-b9e0-4f28-bfda-943debae395c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Queues" Version="12.25.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.2" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AsyncReportEngine.Services.Abstraction\AsyncReportEngine.Services.Abstraction.csproj" />
    <ProjectReference Include="..\AsyncReportEngine.Services\AsyncReportEngine.Services.csproj" />
    <ProjectReference Include="..\AsyncReportEngine.DataAccess.Abstraction\AsyncReportEngine.DataAccess.Abstraction.csproj" />
    <ProjectReference Include="..\AsyncReportEngine.DataAccess\AsyncReportEngine.DataAccess.csproj" />
    <ProjectReference Include="..\AsyncReportEngine.Shared\AsyncReportEngine.Shared.csproj" />
  </ItemGroup>
</Project>
